{% set name = "phconvert" %}
{% set version = "0.8.1" %}
{% set sha256 = "c042e68c7bf56e2ec1f7dd04bf75e6a22db9cff179f482b254e88843c6e9e463" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/Photon-HDF5/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - numpy >=1.9
    - pytables
    - future

test:
  imports:
    - phconvert

about:
  home: http://photon-hdf5.github.io/phconvert
  license: MIT
  license_file: LICENSE.txt
  summary: 'Convert and write Photon-HDF5 files.'
  description: |
    *phconvert* is a python 2 & 3 library that helps writing valid
    Photon-HDF5 <http://photon-hdf5.org/>
    files, a file format for time stamp-based single-molecule spectroscopy.
    Additionally, phconvert can convert all the common binary formats
    used in in single-molecule spectroscopy (e.g. PicoQuant .HT3,
    Becker & Hickl .SPC/.SET) to Photon-HDF5.
  doc_url: http://phconvert.readthedocs.io/
  dev_url: https://github.com/Photon-HDF5/phconvert

extra:
  recipe-maintainers:
    - tritemio
