travis:
  secure:
    BINSTAR_TOKEN: FdviX52gQXLjdLxn7lfJzyvY98cZMiRXHo8UucDCvyn20cs+UTQvdJSC5na+d7LiBOaIQXq2/xGRYXRv5vWpX0MySBm7g03Eb3jNUNJhxbSsrJhY6FZ0TWUaSln5lkgOsZv5O1tcEa1bFZ9wC1xQgLW9Y8bnah3NAcG7gmybz/VVZeyZ47iH8UuBlETicL5f8xen3AOdLquaeVg6D157+sNEFM/I0RwRIXnhlvM1CCUrbcEMNtPEW2KYf5zIbIZI072qZ9xYUw1YbZnzONo+fsC55EzuHGwyUBhCZuMxiiE8/IQZDsru4c0P5rwvJzHP/VEMdqpsZZiGUSnNuE5JJg2lKYssbTL+Bp2ESiooq5quwt0DmrqjpuZoETqGUzjWZCAVH5AV1TaZvMBTSgIgdtpvEsX5AL8xV2qSpbFYBXYsdLbJaapCP8QsX3dOsQDUgWKAKHFp5ZDcPoFkOUmxicY0GbpIPSsPxSa7jRHiRRKhvgQngL+DdkAXZz7L5b7p8NGav7a8ZKzd2cAxJILbxOkVfhkeu8E6jSCOi4KKE3Daxxddhf+CNKABxPT7qLdMbgyyBz7bDeuE6cM2GeCxzarpTJz5PbUMt1XMRI8KAIPtkON7AQ3qYwMdPBKUrMhdirXyK/9ELxyzaAelIs9lj9/NDtnAgvZnKTzFBV+Hsno=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
