travis:
  secure:
    BINSTAR_TOKEN: W2KHh3hSSyB9exTOWv2cOkbM9D3WFLzdLaZP8kL/ixerlEjPaF6vTo6NaCNi8YkeIF/YmcWBxj2x2xX9UviI/cPAK7V7IXQ9DNS4C0X4y+rz7iyX625NQhBrkaXrCsiYdKrwrH8l/1Sx6fBcJJwl1J+iPu0kwjkM4ZjKar+F3PVlmDYW5mVmbkqUC5vjjWLyF+/ZYAdowumAVNoffv8172FBebxF/d9r1N4xHCsBJREPiUoeTCDbcY+/fQyNbhh68ic6OWQKhcl4zKuUkdrn28hM0Q+1NlKNzxChA+WMOl2sd9zo5xiCp4TmlWwy+FCpE9yW0cN5huhtK1x3uwdNqCABNRR12pp4CLF4HFgw8LefQ2eVPMrt1Ja5FXWzoPyrLKvrwP5T5UT5gIF+FMZ030oIdm6vYB9ouDOx27CbmgSv6YJ3wkuwIu0AR1sCH+/+vpw5jS48i4yOrbNZ/OLpKtkzxQ9RyYKA1YmIhxmiopG7eCehY++ExTXGqjCnrBlg/m7AdIB1p+9daRXeb7p+xSimbajeJEcfTCIBououijEHjrqpPkEJF2Q6suboLeooB1Y8CSTffiz+WBUGKozbAvQH1So7KfWpBXsqQrM27FeMENOtRrAdCuaJRAL0cPnAQsKbP4dy4seBrxqrCVEOiv57RoFA/TEUv5o7siRf6nw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
