travis:
  secure:
    BINSTAR_TOKEN: lwVneQu3GpmPdZfOaM20ekLX1KIy+xUYnk/i8Brx6VlcCGy6QqZjgUc/ncx3RofNY1OjSg+PME9R2LSpCBSeqbdtvZBrHL5rBoLULOlLPV1liVXz5+lm0EfusxMsOWwrAxjEtCHKTzpajIBnjIX1AJ+bP4G6s0hT5SzwSdmnWvOf8x/YX4Cp8dya2oSFEJ46ZHhjKcgX/QvoH53P30r1bwR3mPOqR7ZVMYa0DgnH3ycxW6DRH1JMN20yt+cX/uRmgsSaHntsxtl91QfAHcSt8/X1SLfoacklIc6gzK8B7Y4tb/VLkqLELy9k2MmQNhAT+Cc9mcqap7XIlrdcAW1YN/gCphM3H8uf4Ydx5yOYLyzhTCHA1pMwrmQlLp8mvmeJZIFDJVLvXEfvk5APZxC4RJqgI2kPmSDeOFEd7lk3XjSuvlTy6lTwrL4Bbn6II64HcPlGqDi1Jix27vDKm1WQ1guRw51k7xbN+Oqhnjoqvd4ZV7Er6L08h+A+5jdBgyC/iyxC6We91WfydCIzQpA3kFduJ2BG+2GkXTT5jGc7SLmyE1UIgrnxzWtNXAuDUchIKB1kpWVYUs1XKyS0gzuLliZYJYi5dJA/v84TrypiuEezSK5gYBqJuxSS0aeHpm5gAmTfkEH/Sz8lHYjxCHqk6ps+HH7mR5TqIGFfX/RL6rU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
